spring:
  application:
    name: aigineer
  datasource:
    hikari:
      pool-name: aiginner-hikari-pool

datasource:
  url: ${DB_URI:jdbc:postgresql://localhost:6432/aigineer_db}
  username: ${DB_USR:postgres}
  password: ${DB_PASS:postgres}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

gigachat:
  auth-key: ${GIGA_CHAT_AUTH_TOKEN}
